### ISSUE TITLE
Update to MP Config 2.0

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye#2]
High Level Overview for MP Config 2.0 from https://github.com/eclipse/microprofile-config/issues?q=is%3Aissue+milestone%3A%22MP+Config+2.0%22

- [x] Expose Conversion in Config API - https://github.com/eclipse/microprofile-config/issues/492
- [x] Configuration Profiles - https://github.com/eclipse/microprofile-config/issues/418
- [x] External Configuration Files - https://github.com/eclipse/microprofile-config/issues/422
- [x] Config Value Metadata - https://github.com/eclipse/microprofile-config/issues/43
- [x] Variable Replacement -  - https://github.com/eclipse/microprofile-config/issues/118
